### ISSUE TITLE
HAN

### ISSUE THREAD

**Issue by ZzzD97** [yongzhuo/Keras-TextClassification#42]
运行HAN模型时出现这个问题：ValueError: Dimensions must be equal, but are 32000 and 64 for 'model_3/bidirectional_1/MatMul' (op: 'MatMul') with input shapes: [?,32000], [64,768]. 请问怎么解决？

**Comment by yongzhuo** [comment]
没有遇到这种情况，请发一下完整的日志，超参数，python, keras, tensorflow环境等

**Comment by ZzzD97** [comment]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 32000 and 64 for 'model_3/bidirectional_1/MatMul' (op: 'MatMul') with input shapes: [?,32000], [64,768].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/gihub/mylab/HAN_train.py", line 89, in <module>
    train(rate=0.01)  # sample条件下设为1,否则训练语料可能会很少
  File "E:/gihub/mylab/HAN_train.py", line 70, in train
    graph = Graph(hyper_parameters)
  File "E:\gihub\mylab\HAN_graph.py", line 63, in __init__
    super().__init__(hyper_parameters)
  File "E:\gihub\mylab\graph.py", line 63, in __init__
    self.create_model(hyper_parameters)
  File "E:\gihub\mylab\HAN_graph.py", line 74, in create_model
    x_word = self.word_level()(x_input_word)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\network.py", line 583, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\network.py", line 740, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\wrappers.py", line 530, in call
    initial_state=forward_state, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 1691, in call
    initial_state=initial_state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 682, in call
    input_length=timesteps)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 3103, in rnn
    input_length=input_length)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 4027, in rnn
    input_time_zero, tuple(initial_states) + tuple(constants))
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 673, in step
    return self.cell.call(inputs, states, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\recurrent.py", line 1452, in call
    matrix_x = K.dot(inputs, self.kernel)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 1373, in dot
    out = tf.matmul(x, y)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 2798, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 5626, in mat_mul
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1786, in __init__
    control_input_ops)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 32000 and 64 for 'model_3/bidirectional_1/MatMul' (op: 'MatMul') with input shapes: [?,32000], [64,768].
使用python=3.7  keras=2.3.1 tensorflow=2.1.0

**Comment by yongzhuo** [comment]
tensorflow2没有不支持，请使用tensorflow-1.15的
