### ISSUE TITLE
运行 Deep_Emoji 出错  TypeError:

### ISSUE THREAD

**Issue by ltaatl** [yongzhuo/Keras-TextClassification#49]
graph init ok!
Traceback (most recent call last):
  File "/home/yons/lta/Keras-TextClassification-master/keras_textclassification/m10_DeepMoji/train.py", line 110, in <module>
    train(rate=1)
  File "/home/yons/lta/Keras-TextClassification-master/keras_textclassification/m10_DeepMoji/train.py", line 95, in train
    pt = PreprocessSim(path_model_dir)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by yongzhuo** [comment]
模型测试其他场景残留的代码，已修复
