### ISSUE TITLE
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'

### ISSUE THREAD

**Issue by xkungfu** [yongzhuo/Keras-TextClassification#50]
执行\Keras-TextClassification\keras_textclassification\m00_Bert\train.py时报错：

```

load bert model start!

Traceback (most recent call last):
  File "train.py", line 109, in <module>
    train(rate=1) # sample条件下设为1,否则训练语料可能会很少
  File "train.py", line 88, in train
    graph = Graph(hyper_parameters)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/m00_Bert/graph.py", line 43, in __init__
    super().__init__(hyper_parameters)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/base/graph.py", line 62, in __init__
    self.create_model(hyper_parameters)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/m00_Bert/graph.py", line 53, in create_model
    super().create_model(hyper_parameters)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/base/graph.py", line 103, in create_model
    self.word_embedding = Embeddings(hyper_parameters=hyper_parameters)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/base/embedding.py", line 199, in __init__
    super().__init__(hyper_parameters)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/base/embedding.py", line 71, in __init__
    self.build()
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_textclassification/base/embedding.py", line 212, in build
    trainable=self.trainable)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_bert/loader.py", line 169, in load_trained_model_from_checkpoint
    **kwargs)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_bert/loader.py", line 58, in build_model_from_config
    **kwargs)
  File "/home/datad/pyroot/similartextKT/env/lib/python3.6/site-packages/keras_bert/bert.py", line 126, in get_model
    adapter_activation=gelu,
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'
```

**Comment by xkungfu** [comment]
pip install keras-bert==0.81.1 slove the problem

**Comment by yongzhuo** [comment]
我这边keras-bert==0.81.0没有出现该问题
