### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by maoliang123** [yongzhuo/Keras-TextClassification#58]
E:\re\code\Keras-TextClassification-master\envs\Keras-TextClassification-master\Scripts\python.exe E:/re/code/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py
Using TensorFlow backend.
2021-03-15 20:33:51.514570: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
load word2vec start!
load word2vec end!
WARNING:tensorflow:From E:\python\lib\site-packages\tensorflow\python\util\deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
Traceback (most recent call last):
  File "E:\python\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "E:\python\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 5 but is 3 for 'capsule_bojone_1/transpose_7' (op: 'Transpose') with input shapes: [?,16,16,16,?], [3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/re/code/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py", line 93, in <module>
    train(rate=1)
  File "E:/re/code/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py", line 74, in train
    graph = Graph(hyper_parameters)
  File "E:\re\code\Keras-TextClassification-master\keras_textclassification\m13_CapsuleNet\graph.py", line 30, in __init__
    super().__init__(hyper_parameters)
  File "E:\re\code\Keras-TextClassification-master\keras_textclassification\base\graph.py", line 64, in __init__
    self.create_model(hyper_parameters)
  File "E:\re\code\Keras-TextClassification-master\keras_textclassification\m13_CapsuleNet\graph.py", line 53, in create_model
    share_weights=True)(x)
  File "E:\python\lib\site-packages\keras\engine\base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "E:\re\code\Keras-TextClassification-master\keras_textclassification\keras_layers\capsule.py", line 276, in call
    b = K.permute_dimensions(b, (0, 2, 1))  # shape = [None, input_num_capsule, num_capsule]
  File "E:\python\lib\site-packages\keras\backend\tensorflow_backend.py", line 2203, in permute_dimensions
    return tf.transpose(x, perm=pattern)
  File "E:\python\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1476, in transpose
    ret = transpose_fn(a, perm, name=name)
  File "E:\python\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 10157, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "E:\python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 3292, in create_op
    compute_device=compute_device)
  File "E:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 3332, in _create_op_helper
    set_shapes_for_outputs(op)
  File "E:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2496, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "E:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2469, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "E:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2399, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "E:\python\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "E:\python\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension must be 5 but is 3 for 'capsule_bojone_1/transpose_7' (op: 'Transpose') with input shapes: [?,16,16,16,?], [3].

**Comment by maoliang123** [comment]
i have not changed the code,just run it.but i get this problem.

**Comment by maoliang123** [comment]
the version of keras is wrong....sorry.
