### ISSUE TITLE
ValueError: Error when checking target: expected dense_1 to have shape (1,) but got array with shape (17,)

### ISSUE THREAD

**Issue by horacioHao** [yongzhuo/Keras-TextClassification#59]
你好，出现以下问题怎么解决，非常感谢

Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py", line 93, in <module>
    train(rate=1)
  File "D:/PycharmProjects/pythonProject/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py", line 88, in train
    graph.fit(x_train, y_train, x_val, y_val)
  File "D:\PycharmProjects\pythonProject\Keras-TextClassification-master\keras_textclassification\base\graph.py", line 150, in fit
    callbacks=self.callback())
  File "D:\Anaconda\envs\py36\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "D:\Anaconda\envs\py36\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "D:\Anaconda\envs\py36\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_1 to have shape (1,) but got array with shape (17,)

**Comment by yongzhuo** [comment]
你错误信息里边提示的是模型输出output和训练数据输入shape不一致，你改了什么或者是用了非默认的网络结构吗？我本地测试没有出现过该问题。方便贴一下代码和超参数么

**Comment by horacioHao** [comment]
> 你错误信息里边提示的是模型输出output和训练数据输入shape不一致，你改了什么或者是用了非默认的网络结构吗？我本地测试没有出现过该问题。方便贴一下代码和超参数么

你好，代码没有改过，都是按照您在README中的操作运行的capsule，报的这个错误，之前是在python2.7的环境下运行的报的错，改成python3.6运行同样是报这个错误。


load word2vec start!
load word2vec end!
________________________________________________________________________________________________________________________
Layer (type)                           Output Shape               Param #       Connected to                            
========================================================================================================================
input_1 (InputLayer)                   (None, 55)                 0                                                     
________________________________________________________________________________________________________________________
embedding_1 (Embedding)                (None, 55, 300)            16200         input_1[0][0]                           
________________________________________________________________________________________________________________________
spatial_dropout1d_1 (SpatialDropout1D) (None, 55, 300)            0             embedding_1[0][0]                       
________________________________________________________________________________________________________________________
conv1d_1 (Conv1D)                      (None, 53, 300)            270300        spatial_dropout1d_1[0][0]               
________________________________________________________________________________________________________________________
conv1d_2 (Conv1D)                      (None, 52, 300)            360300        spatial_dropout1d_1[0][0]               
________________________________________________________________________________________________________________________
conv1d_3 (Conv1D)                      (None, 51, 300)            450300        spatial_dropout1d_1[0][0]               
________________________________________________________________________________________________________________________
capsule_bojone_1 (Capsule_bojone)      (None, 16, 16)             76800         conv1d_1[0][0]                          
________________________________________________________________________________________________________________________
capsule_bojone_2 (Capsule_bojone)      (None, 16, 16)             76800         conv1d_2[0][0]                          
________________________________________________________________________________________________________________________
capsule_bojone_3 (Capsule_bojone)      (None, 16, 16)             76800         conv1d_3[0][0]                          
________________________________________________________________________________________________________________________
concatenate_1 (Concatenate)            (None, 16, 48)             0             capsule_bojone_1[0][0]                  
                                                                                capsule_bojone_2[0][0]                  
                                                                                capsule_bojone_3[0][0]                  
________________________________________________________________________________________________________________________
flatten_1 (Flatten)                    (None, 768)                0             concatenate_1[0][0]                     
________________________________________________________________________________________________________________________
dropout_1 (Dropout)                    (None, 768)                0             flatten_1[0][0]                         
________________________________________________________________________________________________________________________
dense_1 (Dense)                        (None, 90)                 69210         dropout_1[0][0]                         
========================================================================================================================
Total params: 1,396,710
Trainable params: 1,380,510
Non-trainable params: 16,200
________________________________________________________________________________________________________________________
  0%|          | 0/100 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\HaoJi\AppData\Local\Temp\jieba.cache
graph init ok!
ques to index start!
Loading model cost 0.436 seconds.
Prefix dict has been built succesfully.
100%|██████████| 100/100 [00:00<00:00, 224.24it/s]
100%|██████████| 100/100 [00:00<?, ?it/s]
label to onehot start!
100%|██████████| 100/100 [00:00<00:00, 11096.34it/s]
100%|██████████| 100/100 [00:00<?, ?it/s]
ques to index start!
label to onehot start!
data propress ok!
100
Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py", line 94, in <module>
    train(rate=1)
  File "D:/PycharmProjects/pythonProject/Keras-TextClassification-master/keras_textclassification/m13_CapsuleNet/train.py", line 89, in train
    graph.fit(x_train, y_train, x_val, y_val)
  File "D:\PycharmProjects\pythonProject\Keras-TextClassification-master\keras_textclassification\base\graph.py", line 150, in fit
    callbacks=self.callback())
  File "D:\Anaconda\envs\py36\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "D:\Anaconda\envs\py36\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "D:\Anaconda\envs\py36\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_1 to have shape (90,) but got array with shape (17,)

Process finished with exit code 1

**Comment by yongzhuo** [comment]
看着像是你设置label=90，但是实际上训练数据集中只有17个类别？

**Comment by horacioHao** [comment]
> 看着像是你设置label=90，但是实际上训练数据集中只有17个类别？

你好，不好意思耽误了几天，没有改过您的代码，也没有设置过label

**Comment by yongzhuo** [comment]
如果没有替换过数据集，就更新到最新的代码试试呢。否则如果用的是自己的数据集，要更新一下label这个参数

**Comment by horacioHao** [comment]
> 如果没有替换过数据集，就更新到最新的代码试试呢。否则如果用的是自己的数据集，要更新一下label这个参数

你好，改了label这个参数，可以了，谢谢！
但是在train的时候出现了这个错误
Epoch 1/20
2021-04-26 17:45:11.335715: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
2021-04-26 17:45:11.335863: I tensorflow/stream_executor/stream.cc:5049] [stream=00000223C1A0D740,impl=00000223C0443220] did not memzero GPU location; source: 00000095EB41E700
2021-04-26 17:45:11.335955: I tensorflow/stream_executor/stream.cc:309] did not allocate timer: 00000095EB41E6C0
2021-04-26 17:45:11.336011: I tensorflow/stream_executor/stream.cc:2050] [stream=00000223C1A0D740,impl=00000223C0443220] did not enqueue 'start timer': 00000095EB41E6C0
2021-04-26 17:45:11.336095: I tensorflow/stream_executor/stream.cc:2062] [stream=00000223C1A0D740,impl=00000223C0443220] did not enqueue 'stop timer': 00000095EB41E6C0
2021-04-26 17:45:11.336172: F tensorflow/stream_executor/cuda/cuda_timer.cc:65] Check failed: start_event_ != nullptr && stop_event_ != nullptr 

Process finished with exit code -1073740791 (0xC0000409)

**Comment by yongzhuo** [comment]
看着像是哪个包安装有问题呢，pycharm问题或者是硬件什么的呢
